/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package metrobuscaminas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author adcd_
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null); //CEntrar ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cargarJuego = new javax.swing.JButton();
        inicioPartida = new javax.swing.JButton();
        inputBomba = new javax.swing.JTextField();
        inputColumna = new javax.swing.JTextField();
        inputFila = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("MetroBuscaminas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Cargar partida");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nueva partida");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel4.setText("Número de bombas:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel5.setText("Número de columnas:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel6.setText("Número de filas:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        cargarJuego.setText("Cargar juego");
        cargarJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarJuegoActionPerformed(evt);
            }
        });
        jPanel1.add(cargarJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        inicioPartida.setText("Iniciar Partida");
        inicioPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioPartidaActionPerformed(evt);
            }
        });
        jPanel1.add(inicioPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 120, -1));
        jPanel1.add(inputBomba, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 120, -1));
        jPanel1.add(inputColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 120, -1));
        jPanel1.add(inputFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 475));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarJuegoActionPerformed
       JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos CSV (*.csv)", "csv");
        fc.setFileFilter(filter);
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String line;
                br.readLine(); // Leer la cabecera
                if ((line = br.readLine()) != null) {
                    String[] values = line.split(",");
                    int filas = Integer.parseInt(values[0]);
                    int columnas = Integer.parseInt(values[1]);
                    int bombas = Integer.parseInt(values[2]);
                    Juego juego = new Juego(filas, columnas, bombas);
                    this.setVisible(false);
                    juego.setVisible(true);
                }
            } catch (IOException | NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Error al cargar el archivo.");
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_cargarJuegoActionPerformed

    private void inicioPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioPartidaActionPerformed
        String filas = inputFila.getText().trim();
        String columnas = inputColumna.getText().trim();
        String bombas = inputBomba.getText().trim();

        if (filas.isEmpty() || columnas.isEmpty() || bombas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los campos no pueden estar vacíos.");
        } else {
            try {
                int numeroFilas = Integer.parseInt(filas);
                int numeroColumnas = Integer.parseInt(columnas);
                int numeroBombas = Integer.parseInt(bombas);

                // Validación de rango para filas y columnas
                if (numeroFilas < 3 || numeroFilas > 10 || numeroColumnas < 3 || numeroColumnas > 10) {
                    JOptionPane.showMessageDialog(this, "Filas y columnas deben estar entre 3 y 10.");
                    return; // Salir del método si la validación falla
                }

                // Validación de bombas
                int maxBombas = numeroFilas * numeroColumnas;
                if (numeroBombas > maxBombas) {
                    JOptionPane.showMessageDialog(this, "El número de bombas no puede exceder " + maxBombas + ".");
                    return; // Salir del método si la validación falla
                }
                if (numeroBombas < 0){
                    JOptionPane.showMessageDialog(this, "El número de bombas no puede ser negativo");
                    return;
                }

                Juego juego = new Juego(numeroFilas, numeroColumnas, numeroBombas);
                this.setVisible(false);
                juego.setVisible(true);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Los campos deben contener solo números enteros.");
            }
        }
    }//GEN-LAST:event_inicioPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargarJuego;
    private javax.swing.JButton inicioPartida;
    private javax.swing.JTextField inputBomba;
    private javax.swing.JTextField inputColumna;
    private javax.swing.JTextField inputFila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
